// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARVfiJvf8bT4x2QmPJb_PTlhnAonXWqcI',
    appId: '1:4408527130:web:7a07c3d9e0001ab16c84a3',
    messagingSenderId: '4408527130',
    projectId: 'arectech-5896a',
    authDomain: 'arectech-5896a.firebaseapp.com',
    storageBucket: 'arectech-5896a.appspot.com',
    measurementId: 'G-1XV2GPHMSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf8l1zl3WuoGhutxAQH7woCd0M3zPRvKw',
    appId: '1:4408527130:android:df28ce46a7eb638b6c84a3',
    messagingSenderId: '4408527130',
    projectId: 'arectech-5896a',
    storageBucket: 'arectech-5896a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByH4K8g6IS8sRX8QwJzK-38B9hcvw6-lw',
    appId: '1:4408527130:ios:dec1f03498c4472b6c84a3',
    messagingSenderId: '4408527130',
    projectId: 'arectech-5896a',
    storageBucket: 'arectech-5896a.appspot.com',
    iosClientId: '4408527130-48sin4d1tslvmrsmqlh7p8ng54kluhru.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByH4K8g6IS8sRX8QwJzK-38B9hcvw6-lw',
    appId: '1:4408527130:ios:7b371a76e78398f66c84a3',
    messagingSenderId: '4408527130',
    projectId: 'arectech-5896a',
    storageBucket: 'arectech-5896a.appspot.com',
    iosClientId: '4408527130-aj4m85retbvsjq83hviq3cjkcsmae38s.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing',
  );
}
